name: Trigger auto deployment for flask-tka

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/flask-tka-AutoDeployTrigger-dc34aa28-1a97-4c85-beba-76d3e51205ef.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.FLASKTKA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FLASKTKA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FLASKTKA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: reynoldputra.azurecr.io
          registryUsername: ${{ secrets.FLASKTKA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FLASKTKA_REGISTRY_PASSWORD }}
          containerAppName: flask-tka
          resourceGroup: fp-tka
          imageToBuild: reynoldputra.azurecr.io/flask-tka:${{ github.sha }}
          dockerfilePath: Dockerfile


