name: Trigger auto deployment for flask-open

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/flask-open-AutoDeployTrigger-0c98aeff-74dc-4cc3-a1e5-5c055b4672c4.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.FLASKOPEN_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FLASKOPEN_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FLASKOPEN_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: reynoldputra.azurecr.io
          registryUsername: ${{ secrets.FLASKOPEN_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FLASKOPEN_REGISTRY_PASSWORD }}
          containerAppName: flask-open
          resourceGroup: tka-c3-fp
          imageToBuild: reynoldputra.azurecr.io/flask-open:${{ github.sha }}
          dockerfilePath: Dockerfile


